LabManual/LabManual/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls"))
]

LabManual/home/urls.py
from django.urls import path

from . import views

app_name = "mainsite"

urlpatterns = [
    #path("", views.welcome, name="home"), #go to views.index
    path("login", views.loginpage, name="login"),
    path("logout", views.logoutUser, name="userexit"),

    path("", views.home, name="home"),
    path("search/<str:pk>", views.searchpage, name="search"),
    path("about", views.about_us, name="aboutus"),
    path("contact", views.contact, name="contact"),

    # Profile URLS
    path("profile", views.profile, name="profile"),
    path("profile/edit", views.editProfile, name="editprofile"),
    path("profile/courses", views.editCourse, name="editcourse"),

    # Lab Manual URLS
    path("create", views.createlab, name='newlab'),
    path("view/<str:pk>", views.viewlab, name='viewlab'),
    path("edit/<str:pk>", views.editlab, name='editlab'),
    path("share/<str:pk>", views.sharedlab, name='sharinglist'),

    path("download/teacher/<str:pk>", views.TeacherDocument, name='teacherdownload'),
]

LabManual/home/models.py
from tkinter import CASCADE
from tokenize import Name
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User, Group
from ckeditor.fields import RichTextField

# Custom Authentication
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    def _create_user(self, email, password=None, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=255)
    last_name  = models.CharField(max_length=255)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    def __str__(self):
        return (f"{self.first_name} {self.last_name}")

# Create your models here.
# class user_info(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     name = models.AutoField(primary_key=True)
#     email = models.EmailField(null=True, blank=True, max_length=255)
#     
#     def __str__(self):
#         return f"User {self.id} is {self.name}"

class Courses(models.Model):
    
    course_code = models.CharField(max_length=255, primary_key=True)
    course_title = models.CharField(max_length=255)
    department = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.course_code} - {self.course_title}"

class CourseInstructor(models.Model):
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="CourseInstructor")
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, related_name="CourseInformation")

    def __str__(self):
        return f"{self.course}"
class Lab_Manual(models.Model):
    lab_name = models.CharField(max_length=255)
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="LabInstructor")
    course = models.ForeignKey(CourseInstructor, on_delete=models.CASCADE, related_name="Courseinformation")
    activity_name = models.CharField(max_length=255)
    activity_no = models.FloatField()
    objectives = models.TextField(blank=True, null=True)
    ilo = models.TextField(blank=True, null=True)
    discussion = models.TextField(blank=True, null=True)
    resources = models.TextField(blank=True, null=True)
    procedure =models.TextField(blank=True, null=True)
    results = models.TextField(blank=True, null=True)
    supplementary = models.TextField(blank=True, null=True)
    observation = models.TextField(blank=True, null=True)
    conclusion = models.TextField(blank=True, null=True)
    # objectives = RichTextField(blank=True, null=True)
    # ilo = RichTextField(blank=True, null=True)
    # discussion = RichTextField(blank=True, null=True)
    # resources = RichTextField(blank=True, null=True)
    # procedure =RichTextField(blank=True, null=True)
    # results = RichTextField(blank=True, null=True)
    # supplementary = RichTextField(blank=True, null=True)
    # observation = RichTextField(blank=True, null=True)
    # conclusion = RichTextField(blank=True, null=True)

    def __str__(self):
        return f"Activity {self.activity_no} entitled {self.activity_name}"

class Sharing(models.Model):
    LabManual = models.ForeignKey(Lab_Manual, on_delete=models.CASCADE, related_name="LabInformation")
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="SharedTo")

    def __str__(self):
        return f"{self.LabManual.activity_name} is shared to {self.instructor.__str__()}"

LabManual/home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import *

from django.contrib.auth import get_user_model


class UserAdminCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name']

class EditProfile(ModelForm):
    class Meta:
        model = CustomUser
        fields= ['first_name',
        'last_name',
        'password'
        ]

class SearchLab(ModelForm):
    class Meta:
        model = Lab_Manual
        fields = ['lab_name',
        'instructor',
        'course',
        'activity_name',
        ]
        

class NewCourse(ModelForm):
    class Meta:
        model = CourseInstructor
        fields = '__all__'

        

class NewLab(ModelForm):
    class Meta:
        model = Lab_Manual
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':"createlabinput"})

    
class ShareLab(ModelForm):
    class Meta:
        model = Sharing
        fields = '__all__'
        

LabManual/home/views.py
# Imports
from multiprocessing import context
from tkinter import Widget
from xml.dom.minidom import Document
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
import requests

from .models import *
from .filters import LabFilter
from .forms import *

from docx import *
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from mailmerge import MailMerge
from bs4 import BeautifulSoup
from html.parser import HTMLParser
from docxtpl import DocxTemplate, RichText
from htmldocx import HtmlToDocx


# Class for html parser
# class DocumentHTMLParser(HTMLParser):
#     def __init__(self, document):
#         HTMLParser.__init__(self)
#         self.document = document
#         self.paragraph  = None
#         self.run = None
    
#     def add_paragraph_and_feed(self, html):
#         self.paragraph = self.document.add_paragraph()
#         self.feed(html)

#     def handle_starttag(self, tag, attrs):
#         self.run = self.paragraph.add_run()

#         if tag in ["ul"]:
#             self.run.add_break()
#         if tag in ["li"]:
#             self.run.add_text(u'        \u2022    ')

#     def handle_endtag(self, tag):
#         if tag in ["li"]:
#             self.run.add_break()
    
#     def handle_data(self, data):
#         self.run.add_text(data)

# Create your views here.
# ----------------- Document Download ----------------- #

# def testTeacherDocument(request, pk):
#     user = request.user
#     labmanual = Lab_Manual.objects.get(id=pk)

#     template = os.path.join(settings.TEMPLATE_ROOT, 'labtemplate.docx')
#     docxdocument = DocxTemplate(template)
#     desc_document = Document()
#     new_parser = HtmlToDocx()
    
#     new_parser.add_html_to_document(labmanual.objectives, desc_document)
#     desc_document.save(os.path.join(settings.TEMPLATE_ROOT, f'subdoc.docx'))

#     # doc_html_parser = DocumentHTMLParser(docxdocument)
#     # test = doc_html_parser.add_paragraph_and_feed(labmanual.objectives)
#     # print(test)

#     sub_doc = docxdocument.new_subdoc(os.path.join(settings.TEMPLATE_ROOT, f'subdoc.docx'))

#     context = {
#         'objectives': sub_doc,

#     }


#     docxdocument.render(context)
#     docxdocument.save(os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.docx'))

    
#     # docxdocument.render(context)

#     # docxdocument.write(os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.docx'))

#     file_dir = os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.docx')
#     if os.path.exists(file_dir):
#         with open(file_dir, 'rb') as fh:
#             response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
#             response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_dir)
#             print('gumana')
#             return response

#     # Renderer.Renderer.Write(os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.rtf'))

#     return redirect('mainsite:viewlab', pk=pk)

def TeacherDocument(request, pk):
    user = request.user
    labmanual = Lab_Manual.objects.get(id=pk)

    template = os.path.join(settings.TEMPLATE_ROOT, 'labtemplate.docx')
    docxdocument = MailMerge(template)

    docxdocument.merge(
    title=f'{labmanual.activity_name}',
    actno=f'{labmanual.activity_no}',
    coursecode=f'{labmanual.course.course.course_code}',
    coursetitle=f'{labmanual.course.course.course_title}',
    instructor=f'{labmanual.instructor}',
    objectives=f'{labmanual.objectives}',
    ilo=f'{labmanual.ilo}',
    discussion=f'{labmanual.discussion}',
    resources=f'{labmanual.resources}',
    procedure=f'{labmanual.procedure}',
    results=f'{labmanual.results}',
    supplementary=f'{labmanual.supplementary}',
    observation=f'{labmanual.observation}',
    conclusion=f'{labmanual.conclusion}'
)
    docxdocument.write(os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.docx'))

    file_dir = os.path.join(settings.TEMPLATE_ROOT, f'{labmanual.lab_name}.docx')
    if os.path.exists(file_dir):
        with open(file_dir, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_dir)
            print('gumana')
            return response

    return redirect('mainsite:viewlab', pk=pk)

# ----------------- Authentication ----------------- #

def loginpage(request):
    if request.user.is_authenticated:
        return redirect('mainsite:home')
    else:
        reg_form = UserAdminCreationForm()
        if 'login-submit' in request.POST:
            if request.method == 'POST':
                email = request.POST.get("email")
                password = request.POST.get("password")

                user = authenticate(request, email=email, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('mainsite:home')
                    
                else:
                    messages.info(request,'Username OR Password is incorrect')
        elif 'register-submit' in request.POST:
            if request.method == 'POST':
                regform = UserAdminCreationForm(request.POST)
                if regform.is_valid():
                    regform.save()
                    messages.success(request, 'Successfully created an account')
                else:
                    messages.success(request, 'Failed to created an account')
                
    context = {'reg_form': reg_form}
    return render(request, "main/authenticate.html", context)

@login_required(login_url='mainsite:login')
def logoutUser(request):
    logout(request)
    return redirect('mainsite:login')

# ----------------- Home ----------------- #

@login_required(login_url='mainsite:login')
def home(request):
    user = request.user
    if request.method == 'POST':
        searched = request.POST['searched']

        return redirect('mainsite:search', pk=searched)
    else:
        labmanuals = Lab_Manual.objects.filter(instructor=user)
        context = {'labmanuals': labmanuals}
        return render(request, "main/home.html", context)

@login_required(login_url='mainsite:login')
def about_us(request):
    return render(request, "main/aboutus.html")

@login_required(login_url='mainsite:login')
def contact(request):
    return render(request, "main/contact.html")

@login_required(login_url='mainsite:login')
def searchpage(request, pk):
    user = request.user
    # pk = pk.split()
    sharinglist = Sharing.objects.filter(instructor=user)
    shared=[]
    # sharinglist = Sharing.objects.all()
    
    if request.method == 'POST':
        searched = request.POST['searched']

        return redirect('mainsite:search', pk=searched)


    labmanuals = Lab_Manual.objects.filter( (Q(lab_name__icontains=pk) | Q(activity_name__icontains=pk) | 
        Q(course__course__course_code__icontains=pk) | 
        Q(course__course__course_title__icontains=pk) | 
        Q(instructor__first_name__icontains=pk) | 
        Q(instructor__last_name__icontains=pk)))

    for field in sharinglist:
        shared.append(field.LabManual)

    return render(request, "main/search.html", {
        'searched': pk,
        'labmanuals': labmanuals,
        'sharinglist': shared,
    })

# ----------------- Profile ----------------- #

@login_required(login_url='mainsite:login')
def profile(request):
    user = request.user
    courselist = CourseInstructor.objects.filter(instructor=user)

    for i in courselist:
        print(i.course.course_code, request.POST)
        if i.course.course_code in request.POST:
            delcourse = CourseInstructor.objects.get(instructor=user, course=i.course)
            delcourse.delete()
            messages.success(request, 'Course successfully Deleted')
    
    if 'eprofile' in request.POST:
        return redirect('mainsite:editprofile')

    context = {"user": user, "courses": CourseInstructor.objects.filter(instructor=user)}
    return render(request, "main/profile.html", context)

@login_required(login_url='mainsite:login')
def editProfile(request):
    user = request.user
    
    form = EditProfile(instance=user)

    context = {"user": user, "form": form}
    return render(request, "main/editprofile.html", context)

@login_required(login_url='mainsite:login')
def editCourse(request):
    user = request.user

    courselist = CourseInstructor.objects.filter(instructor=user)
    courseform = NewCourse(initial={'instructor': user})

    if 'addcourse' in request.POST:
        form = NewCourse(request.POST)
        getcourse = request.POST.get("course")
        if form.is_valid():
            try:
                checkCourse = CourseInstructor.objects.get(instructor=user, course=getcourse)
            except ObjectDoesNotExist:
                form.save()

            messages.success(request, 'Course Already Exist to this user')

    for i in courselist:
        if i.course.course_code in request.POST:
            delcourse = CourseInstructor.objects.get(instructor=user, course=i.course)
            delcourse.delete()
            messages.success(request, 'Course successfully Deleted')

    context = {"user": user, "courses": CourseInstructor.objects.filter(instructor=user) ,"form": courseform}
    return render(request, "main/editcourse.html", context)

# ----------------- Laboratory ----------------- #


LabManual/home/templates/main/aboutus.html
{% extends "main/template.html" %}

{% load static %}

{% block title %}
    Lab Manual Maker - About us
{% endblock %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'css/aboutus.css' %} ? {% now 'U' %}" />
    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
    <div class="bodycontainer">
        <div>
            <img src="{% static 'images/logo.png' %}" id="grouplogo" />
        </div>
        <div class="header">
            <h1>Technological Institute of the Philippines</h1>
            <h2>Department of Computer Engineering</h2>
            <h2>Bachelor of Science in Computer Engineering (BSCpE)</h2>

            <div class="sub-container">
                <div class="students">
                    <img src="{% static 'images/Bonifacio.jpg' %}" class="idpic" />
                    <h2 class="name">J.C. Jeff Bonifacio</h2>
                </div>
                <div class="students">
                    <img src="{% static 'images/Espela.jpg' %}" class="idpic" />
                    <h2 class="name">Emerson Espela</h2>
                </div>
                <div class="students">
                    <img src="{% static 'images/Jasper.png' %}" class="idpic" />
                    <h2 class="name">Jasper Ortega</h2>
                </div>
                <div class="students">
                    <img src="{% static 'images/Reyes.jpg' %}" class="idpic" />
                    <h2 class="name">Jhoanna Reyes</h2>
                </div>
                <div class="students">
                    <img src="{% static 'images/Viernes.png' %}" class="idpic" />
                    <h2 class="name">Kent Jan Viernes</h2>
                </div>
                <div class="students teacher">
                    <img src="{% static 'images/DrTaylar.jpg' %}" class="idpic" />
                    <h2 class="name">Dr. Jonathan Taylar</h2>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

LabManual/home/templates/main/authenticate.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <title>
            Lab Manual Maker - Login
        </title>
        <meta charset="utf-8" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/authenticate.css' %} ? {% now 'U' %}" />
            <div class="bg"></div>
            <div class="bg bg2"></div>
            <div class="bg bg3"></div>
    </head>
    <body>
        <header>
            <img src="{% static 'images/logo.png' %}" id="tiplogo" />
        </header>

        <div class="cont">
            <div class="form sign-in" id="login">
                <form method="POST">
                    <h2>Login</h2>
                    {% csrf_token %}
                    <label>
                    <span for="email">Email</span>
                    <input required id="loginemail" type="email" name="email" />
                    </label>
                    <label >
                    <span for="password">Password</span>
                    <input required id="loginpassword"  type="password" name="password"/>
                    </label>

                    <button class="submit" type="submit" value="Login" id="Login" name="login-submit">Login</button>
                </form>

                {% for message in messages %}
                <p class="notif">{{message}}{{reg_form.errors}}</p>
                {% endfor %}
            </div>

            <div class="sub-cont">
                <div class="img">
                  <div class="img-text m-up">
                    <h2>New here?</h2>
                    <p>Register and discover great amount of new opportunities!</p>
                  </div>
                  <div class="img-text m-in">
                    <h2>One of us?</h2>
                    <p>If you already has an account, just Login.</p>
                  </div>
                  <div class="img-btn">
                    <span class="m-up">Register</span>
                    <span class="m-in">Login</span>
                  </div>
                </div>

                <div class="form sign-up" id="register">
                    <form method="POST">
                        <h2>Register</h2>
                        {% csrf_token %}
                        
                        {% for field in reg_form %}
                        <label>
                            <p>{{field.label}}</p>
                            <p>{{field}}</p>
                        
                        {% endfor %}
                        </label>
                    
                        
                        <button class="submit" type="submit" value="Register" id="Register" name="register-submit">Register</button>
                    </form>
                    {% for message in messages %}
                    <p class="notif">{{message}}{{reg_form.errors}}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        
        <script>
            document.querySelector('.img-btn').addEventListener('click', function()
                {
                    document.querySelector('.cont').classList.toggle('s-signup')
                }
            )
        </script>
    </body>

    
</html>

LabManual/home/templates/main/profile.html
{% extends "main/template.html" %}

{% load static %}

{% block title %}
    Profile
{% endblock %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %} ? {% now 'U' %}" />
    <h1 class="headerprofile">Profile</h1>
    <div class="userinfo-row">
        <div class="editprofile-column profile-wrapper" style="background-color:#B7CDB7;">
            <h2 class="account-txt">Account Settings</h2>
            <p>Full Name: {{ user }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Password: {{ user.password }}</p>
            <form method="POST">
                {% csrf_token %}
                <!---- <input name="eprofile" value="EDIT PROFILE" type="submit"> ---->
            </form>
        </div>
        
        <div class="editcourse-column" style="background-color:#86AB86;">
            <div class="courseDivisionContainer">
                <div class="fixedHeaderContainer">
                    <div class="fixed-header">
                        <h2 class="course-txt">Courses</h2>
                        <a href="{% url 'mainsite:editcourse' %}"><button class="icon-btn add-btn"><div class="add-icon"></div><div class="btn-txt">Add Course</div></button></a>
                    </div>
                </div>
            </div>            
            <div class="editCourseColumnContainer">
                {% for field in courses %}
                <div>
                    <li>
                        <p class="added-course">{{field.course}}</p>
                        <form method="POST">
                            {% csrf_token %}
                            <input name="{{field.course.course_code}}" value="DELETE" type="submit"/>
                        </form>
                    </li>
                </div>
                    {% empty %}
                        <li>No Courses</li>
                {% endfor %}
                
                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

LabManual/home/templates/main/template.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    
        <link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %} ? {% now 'U' %}" />
    </head>
    <body>
        <div id="sidebar" class="sidenav">
            <a href="javascript:void(0)" class="closebtn sidecontent" onclick="closeNav() ">&times;</a>
            <a class="sidecontent" href="{% url 'mainsite:home' %}">Home</a>
            <a class="sidecontent" href="{% url 'mainsite:profile' %}">Profile</a>
            <a class="sidecontent" href="{% url 'mainsite:userexit' %}">Logout</a>
        </div>

        <div id="menubar-container">
            <a href="{% url 'mainsite:home' %}">
                <img src="{% static 'images/TIPLogo.png' %}" id="tiplogo" class="menubar" />
            </a>

            <div id="menuright" class="menu">
                <div class="nav-links" id="navLinks">
                <a class="menubar" href="{% url 'mainsite:home' %}">Home</a>
                <a class="menubar" href="{% url 'mainsite:newlab' %}">Create</a>
                <a class="menubar" href="{% url 'mainsite:aboutus' %}">About Us</a>
                <a class="menubar" href="{% url 'mainsite:contact' %}">Contact</a>
                <img src="{% static 'images/account.png' %}" id="account" class="menubar" onclick="openNav()"/>
                </div>
            </div>
                

        </div>
        
        <div id="main">
            {% block body %}
            {% endblock %}
        </div>

        
    </body>
    <script>
        function openNav(){
            document.getElementById("sidebar").style.width = "250px";
        }
        function closeNav(){
            document.getElementById("sidebar").style.width = "0";
        }

        document.querySelector('#main').addEventListener('click', closeNav)

        
    </script>


    <script>
        var navLinks = document.getElementById("navLinks");
        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }
    </script>



</html>

LabManual/home/templates/main/viewlab.html
{% extends "main/template.html" %}

{% load static %}

{% block title %}
    {{ labelements.lab_name }}
{% endblock %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'css/viewlab.css' %} ? {% now 'U' %}" />
<div class="cont">
    <div>
        <ul>
            <p>Title: <div class="contentlabel">{{labelements.lab_name}}</div></p>
            <p>Instructor:  <div class="contentlabel">{{labelements.instructor}}</div></p>
            <p>Course: <div class="contentlabel">{{labelements.course}}</div></p>
            <p>Activity Name: <div class="contentlabel">{{labelements.activity_name}}</div></p>
            <p>Activity Number: <div class="contentlabel">{{labelements.activity_no | safe}}</div></p>
            <p>Objectives: </p>
                <div class="contentlabel">{{labelements.objectives | safe}}</div>
            <p>Intended Learning Outcomes: </p>
                <div class="contentlabel">{{labelements.ilo | safe}}</div>
            <p>Discussion: </p>
                <div class="contentlabel">{{labelements.discussion | safe}}</div>
            <p>Resources:</p> 
                <div class="contentlabel">{{labelements.resources | safe}}</div>
            <p>Procedure:</p> 
                <div class="contentlabel">{{labelements.procedure | safe}}</div>
            <p>Results: </p>
                <div class="contentlabel">{{labelements.results | safe}}</div>
            <p>Supplementary Tasks: </p>
                <div class="contentlabel">{{labelements.supplementary | safe}}</div>
            <p>Obeservations: </p>
                <div class="contentlabel">{{labelements.observation | safe}}</div>
            <p>Conclusion: </p>
                <div class="contentlabel">{{labelements.conclusion | safe}}</p>

        </ul>
    </div>
    <div class="sub-cont">
        <form method="POST">
            {% csrf_token %}
            
            <button class="download-button">
                <div class="docs"><svg class="css-i6dzq1" stroke-linejoin="round" stroke-linecap="round" fill="none" stroke-width="2" stroke="currentColor" height="20" width="20" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line y2="13" x2="8" y1="13" x1="16"></line><line y2="17" x2="8" y1="17" x1="16"></line><polyline points="10 9 9 9 8 9"></polyline></svg><input type="submit" name="editlab" value="EDIT" /></div> 
            </button>
            <button class="download-button">
                <div class="docs"><svg class="css-i6dzq1" stroke-linejoin="round" stroke-linecap="round" fill="none" stroke-width="2" stroke="currentColor" height="20" width="20" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line y2="13" x2="8" y1="13" x1="16"></line><line y2="17" x2="8" y1="17" x1="16"></line><polyline points="10 9 9 9 8 9"></polyline></svg> <input type="submit" name="teacherdownload" value="DOWNLOAD" /></div> 
            </button>
        </form>
        {% if request.user == labelements.instructor %}
        <button class="download-button">
            <div class="docs"><svg class="css-i6dzq1" stroke-linejoin="round" stroke-linecap="round" fill="none" stroke-width="2" stroke="currentColor" height="20" width="20" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line y2="13" x2="8" y1="13" x1="16"></line><line y2="17" x2="8" y1="17" x1="16"></line><polyline points="10 9 9 9 8 9"></polyline></svg> <input type="submit" onclick="location.href ='{% url 'mainsite:sharinglist' labelements.id %}'" value="SHARE"/></div>
        </button>
         {% endif %}
    </div>
</div>
    

{% endblock %}